### ISSUE TITLE
Script only recovers chat snaps

### ISSUE THREAD

**Issue by stenlan** [sdushantha/snaprecovery#12]
From the description I got the impression that this would recover actual snaps that you received from users. However, I think `chat_snap` isn't the right directory for this. Am I wrong in this assumption? Because it seems like the script is only recovering snaps that have been sent in a chat as opposed to normally.

**Comment by sdushantha** [comment]
This script recovers the normal snaps (images and videos) that people tend to send. By this, I mean the ones that appear as a red square and purple squares that appear when someone sends a photo or a video snap.
