### ISSUE TITLE
Still working or new method available?

### ISSUE THREAD

**Issue by xnvmx** [sdushantha/snaprecovery#13]
I can see on your github page that Snapchat has patched this vulnerability. Is it possible to somehow recover a saved snap in the chat and then deleted after half an hour by the sender? I would like to know if for sure this is possible before rooting the phone and I really care about it...

**Comment by sdushantha** [comment]
I doubt that is possible because of the new patch. But I'll be on the lookout for more bugs :)

Just a tip, don't root your phone if that is the only phone you have and care about it. I luckily rooted an old phone because I had a few failed attempts where I accidentally bricked the device.
